version: "3.8"

services:
  # Angular amorsaude frontend
  # frontend: 
  #   build:
  #     dockerfile: DockerFile
  #     context: ./amorsaude-frontend
  #     target: development
  #   command: npm run start
  #   volumes:
  #     - ./amorsaude-frontend:/projetos/amorsaude/src/app
  #     - /projetos/amorsaude/src/app/node_modules
  #   ports:
  #     - "4200:4200"
  #   depends_on:
  #     - api
  # NestJS amorsaude api
  api: 
    build: 
      dockerfile: DockerFile
      context: ./amorsaude-api
      target: development
    volumes:
      - ./amorsaude-api:/Projetos/amorsaude/app
      - /Projetos/amorsaude/app/node_modules/
    command: npm run start:debug
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/db
    ports:
      - "3000:3000"
      
  postgres: 
    image: postgres:16.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123789456
      POSTGRES_DB: db
    ports:
      - 35000:5432

  postgres_admin:
    image: dpage/pgadmin4:6.12
    depends_on: 
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 5050:80

    
