version: "3.8"

services:
  # NestJS amorsaude api
  api: 
    build: 
      dockerfile: DockerFile
      context: ./amorsaude-api
      target: development
    volumes:
      - ./amorsaude-api:/Projetos/amorsaude/app
      - /Projetos/amorsaude/app/node_modules/
    command: npm run start:debug
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/db
    ports:
      - "3000:3000"
      
  postgres: 
    image: postgres:14.4
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - 35000:5432

  postgres_admin:
    image: dpage/pgadmin4:6.12
    depends_on: 
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 5050:80

    
